#!/bin/bash

# Variables for File Paths
  JAMF_BINARY="/usr/local/bin/jamf"
  CURRENTUSER=$(/usr/bin/python -c 'from SystemConfiguration import SCDynamicStoreCopyConsoleUser; import sys; username = (SCDynamicStoreCopyConsoleUser(None, None, None) or [None])[0]; username = [username,""][username in [u"loginwindow", None, u""]]; sys.stdout.write(username + "\n");')
  FDE_SETUP_BINARY="/usr/bin/fdesetup"
  DEP_NOTIFY_APP="/Applications/Utilities/DEPNotify.app"
  DEP_NOTIFY_LOG="/var/tmp/depnotify.log"
  DEP_NOTIFY_DEBUG="/var/tmp/depnotifyDebug.log"
  DEP_NOTIFY_DONE="/var/tmp/com.depnotify.provisioning.done"
  
  # Array Info for Dropdown Options
  BUILDING_ARRAY=(
        "506 Race St"
        "507 Pine St"
        "ARC"
        "Athletics Complex"
        "Barlow"
        "Bedford"
        "Blackwell Hall"
        "Bristow"
        "Brock"
        "Brock Commons Tennis Courts"
        "Buddy Bolding Stadium"
        "Center for Communication Studies and Theatre"
        "Chichester"
        "Clark House"
        "Cox Hall"
        "Coyner Hall"
        "Crafts House"
        "Curry Hall"
        "Daniel-Hardy House"
        "Dorril Dining Hall"
        "First Avenue Field"
        "Frazer Hall"
        "French Hall"
        "Golf Course"
        "Graham"
        "Grainger"
        "Greenwood Library"
        "Health & Fitness Center"
        "Heating Plant"
        "Hiner"
        "Hull"
        "Iler"
        "Jarman"
        "Jeffers Hall"
        "Lancaster"
        "Lancer Park"
        "Lankford"
        "LCVA"
        "Longwood Bed and Breakfast"
        "Longwood House"
        "Longwood Landings"
        "Longwood Village"
        "Maugans"
        "McCorkle"
        "Ruffner"
        "Stevens"
        "Stubbs Hall"
        "Tabb"
        "Wheeler Hall"
        "Willett"
        "Wygal"
      )
			
	DEPARTMENT_ARRAY=(
        "Academic Affairs"
        "Accounting and Financial Reporting"
        "Accounts Payable"
        "Accreditation & Compliance"
        "Administration and Finance"
        "Admissions"
        "Alumni Relations"
        'Art and TAGAD (Graphic & Animation Design)'
        'Assessment and Institutional Research (OAIR)'
        "Assistant VP of Student Affairs"
        "Athletic Academic Services"
        "Athletics - Administration"
        "Athletics - Facilities/Grounds"
        "Athletics Communications"
        "Biology, Chemistry, Physics and Environmental Sciences"
        "Budget Office"
        "Business and Economics"
        "Campus Planning & Development"
        "Campus Recreation"
        "Capital Design and Construction"
        'CAPS (Counseling Center/Psychology)'
        "Cashiering and Student Accounts"
        "Center for Academic Success"
        'Center for Faculty Enrichment (CAFÉ)'
        "Clean VA Waterways"
        "Communication Sciences & Disorders"
        "Communication Studies"
        "Conferences and Scheduling"
        "Cormier Honors College"
        "Dean of Education and Human Services"
        "Dean, College of Arts & Sciences"
        "Decommissioned"
        'Digital Education Collaborative (DEC)'
        "Dining Services"
        "Disability Resources"
        "Diversity and Inclusion"
        "Education and Special Education"
        "Emergency Management"
        "English and Modern Language"
        "Enrollment Management"
        "Environmental Health and Safety"
        "Facilities Management"
        "Financial Aid"
        "Financial Operations"
        "First Year Experience"
        "Golf Course"
        "Graduate & Professional Studies"
        "Greenwood Library"
        'Health, Athletic Training, Recreation, and Kinesiology (HARK)'
        "History, Political Science, and Philosophy"
        "Hull Springs"
        "Human Resources & Parole"
        "I.T.T.I.P. Institute for Teaching through Technology and Innovative Practices"
        'Information and Instructional Services Technology (ITS)'
        "Internal Audit"
        "International Studies"
        "IT Field Support"
        "LancerCard Center"
        "Landscaping and Grounds Management"
        "Leadership and Service Learning"
        "Liberal Arts/Solstice"
        "Longwood Bed and Breakfast -- University Inn"
        "Longwood Foundation"
        "LVCA"
        "Materiel Management"
        "Math and Computer Science"
        'Military Science (ROTC)'
        "Moton Museum"
        "Motor Pool"
        "Music"
        "Nursing"
        "Office of Sponsored Programs"
        "Office of Student Conduct"
        "Office of Student Research"
        "Operation of Power Plant"
        "Police Department"
        "Post Office"
        "President's Office"
        "Printing Services"
        "Professional Services"
        "Psychology"
        "Public Relations"
        "Real Estate Foundation"
        "Registrar's Office"
        'Residential and Commuter Life (RCL)'
        "Rotunda"
        "SACS Reaffirmation Office"
        "Small Business Development Center"
        "Social Work"
        "Sociology, Anthropology & Criminal Justice Studies"
        "Southside Rural Health Development Center"
        'Speech Hearing and Learning (included with Comm Sciences/Disorders)'
        "Student Health and Wellness Center"
        "Surplus"
        "Theatre"
        "University Advancement"
        "University Career Center"
        "University Center and Student Activities"
        "University Marketing and Communications"
        "Vice President for Student Affairs"
        "Vice President of Facilities & Real Property"
      )
			
	 POLICY_ARRAY=(
        "Installing Adobe Acrobat Pro DC,adobeacrobatprodc"
        "Installing Alertus Desktop,alertusdesktop"
        "Installing BeyondTrust Remote Support,bomgar"
        "Installing Google Chrome,googlechrome"
        "Installing Mozilla Firefox ESR,firefoxesr"
        "Installing Adobe Flash Player,adobeflashplayer"
        "Installing Microsoft Office 2019,office2019"
        "Installing McAfee Antivirus,mcafee"
        "Adding Users To Print Group,lpadmin"
        "Setting Date and Time,datetime"
        "Binding To Active Directory,joindomain"
        "Installing Critical Updates,updateSoftware"
			)
			
